# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admn_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('IT', 'IT'), ('ME', 'ME')], max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('st', 'STUDENT'), ('tu', 'TUTOR'), ('ho', 'HOD'), ('of', 'OFFICE STAFF')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of parent'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
