# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_application_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Application')),
            ],
        ),
        migrations.RenameField(
            model_name='hierarchy',
            old_name='user',
            new_name='designation',
        ),
    ]
