# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-05 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171105_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='Hierarchy',
        ),
        migrations.RemoveField(
            model_name='status',
            name='application',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
