# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-19 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171105_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admn_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
